//1 Write a function that uses reduce to calculate the total amount of money earned by the restaurant from all the orders. Assume that each item costs $10.
const orders = [{
        tableNumber: 1,
        items: ['burger', 'fries', 'soda']
    },
    {
        tableNumber: 2,
        items: ['pizza', 'salad', 'water']
    },
    {
        tableNumber: 3,
        items: ['sandwich', 'soup', 'coffee']
    },
];
// Output 90

const totalAmountEarned = orders => orders.reduce((acc, order) => order.items.length * 10 + acc, 0)

console.log(totalAmountEarned(orders))




//2 Write a function that uses reduce to calculate the total revenue generated by the company from all the sales. Assume that the revenue from each sale is the product of the amount and price.

const sales = [{
        product: 'apple',
        amount: 100,
        price: 1
    },
    {
        product: 'banana',
        amount: 200,
        price: 0.5
    },
    {
        product: 'orange',
        amount: 300,
        price: 0.75
    },
    {
        product: 'grape',
        amount: 400,
        price: 0.4
    },
];


const calculateTotalSales = sales => sales.reduce((acc, {
    amount,
    price
}) => acc + amount * price, 0)

console.log(calculateTotalSales(sales))


//3 Write a function that uses `reduce` to find the user who has the most number of friends.
const users = [{
        id: 1,
        name: 'Alice',
        friends: ["Bob", "Charlie", "David"]
    },
    {
        id: 2,
        name: 'Bob',
        friends: ["Alice", "Charlie", "Eve"]
    },
    {
        id: 3,
        name: 'Charlie',
        friends: ["Alice", "Bob", "David", "Eve"]
    },
    {
        id: 4,
        name: 'David',
        friends: ["Alice", "Charlie"]
    },
    {
        id: 5,
        name: 'Eve',
        friends: ["Bob", "Charlie"]
    },
];


const findMaxFriends = users => users.reduce((acc, user) => acc.friends.length < user.friends.length ? user : acc).name

console.log(findMaxFriends(users))



//4 Write a function that uses reduce to calculate the total revenue generated by the store from all the orders. Assume that the revenue from each order is the sum of the prices of all the items in the order.


const orders = [{
        id: 1,
        items: [{
            name: 'book',
            price: 10
        }, {
            name: 'pen',
            price: 2
        }]
    },
    {
        id: 2,
        items: [{
            name: 'shirt',
            price: 20
        }, {
            name: 'pants',
            price: 30
        }]
    },
    {
        id: 3,
        items: [{
            name: 'hat',
            price: 15
        }, {
            name: 'socks',
            price: 5
        }]
    },
];


const calculateTotalRevenue = orders => orders.reduce((acc, order) => order.items.reduce((acc, item) => acc + item.price, 0) + acc, 0)

console.log(calculateTotalRevenue(orders))


//5 Write a function that uses reduce to calculate the total amount of money earned by the restaurant from all the orders.

// Cost of each item is given below:

const foodPrices = {
    burger: 50,
    fries: 30,
    soda: 8,
    pizza: 60,
    salad: 10,
    water: 2,
    sandwich: 30,
    soup: 10,
    coffee: 100
}
const orders = [{
        tableNumber: 1,
        items: ['burger', 'fries', 'soda']
    },
    {
        tableNumber: 2,
        items: ['pizza', 'salad', 'water']
    },
    {
        tableNumber: 3,
        items: ['sandwich', 'soup', 'coffee']
    },
];

const totalMoneyEarned = orders => orders.reduce((acc, order) => acc + order.items.reduce((acc, item) => foodPrices[item] + acc, 0), 0)

console.log(totalMoneyEarned(orders))